### PR TITLE
[refs #00061] Use Nightingale cookies script

### PR DESCRIPTION
**Pull request by Android63**
Use JavaScript that is built into Nightingale to handle cookies.

@ishanivardhan I had a guess at the path to nodel_modules and wouldn't be surprised if I'm wrong so please feel free to make it right!

### CODE REVIEW

**Comment by ishanivardhan** [comment]
Good attempt @Android63 ! However, there were two things stopping it from working.

1. Your src path for the JS file was incorrect. The file where you have written your code is in `theme/nightingale/templates/core/login.mustache` AND actual JS file sits in `theme/nightingale/node_modules/nightingale/js/cookies.js`

2. Moodle only likes a certain way to include JS either as an AMD module or otherwise into the layout of pages. Instead of putting a `<script>` tag, the JS file needs to be called from the layout of the page you are in. In this case, `theme/nightingale/layout/login/php`

I have corrected the code, tested my fix and it seems to work. 

It'd be worth you having a look at this for future reference. I could get @cehwitham to review this now!

**Review by cehwitham — COMMENTED** [review]
Great team work on this @Android63 and @ishanivardhan. Do we only load the cookie script on the Login page or do we load it on all pages?

**Comment by ishanivardhan** [comment]
Thanks @cehwitham ! This cookie script only loads at login page as it's been included only for that layout. If we need this on other pages, we need to include it from `columns2.php` layout file which is prevalent for all pages.

**Comment by cehwitham** [comment]
It's an interesting topic @ishanivardhan as theoretically people will need to accept cookies to log in and therefore if they're past the login page, it seems irrelevant to have the cookie banner but I wonder if there was a guest access course created for example in future that didn't require people to log in, we'd still need them to accept cookies.

**Comment by Android63** [comment]
Don't people need to accept cookies even if they don't log in? For example, for analytics. If so, we should have the banner on all pages.

**Comment by ishanivardhan** [comment]
@cehwitham , @Android63 - Well, now that the topic has sprung up it makes me think as to regardless of Guest access, should the Cookie banner be on all pages until dismissed?

This is only so if they don't dismiss it on Login page either as a normal or guest user, we don't show this banner again which is allowing a breach of Cookie policy ourselves.

Let me know your thoughts & I can introduce some changes to show Cookie banner on all pages (just above Alpha/Beta Banner) until the user dismisses them. This takes care of Guest user access too.

(I'm sure the user will dismiss it at some point as those are just too annoying hanging at the top :))

**Comment by Android63** [comment]
I think it's quite simple: we display the cookie ribbon on all pages, regardless of logged in status, until the user dismisses it.

**Comment by cehwitham** [comment]
@ishanivardhan we can probably merge this as is and open a new issue to add to other pages.

**Pull request merged**
